### ISSUE TITLE
Form Errrors

### ISSUE THREAD

**Issue by trebird** [trebird/ecommerce-pattern-library#2]
Hi @thomasjbradley,

Working on finishing up my form, but having trouble getting the error messages to work for the smaller fields (Card expiry and CVC) and haven't been able to figure it out.

**Comment by thomasjbradley** [comment]
There are some attributes missing on their `<input>` tags. See this working one here:
https://github.com/trebird/ecommerce-pattern-library/blob/master/_patterns/form/checkout-form.html#L38

And compare with one that isn’t working:
https://github.com/trebird/ecommerce-pattern-library/blob/master/_patterns/form/checkout-form.html#L47

**Comment by trebird** [comment]
Indeed, those were some bare looking inputs.

Thank you!

**Comment by trebird** [comment]
Hi again!

I have a style-related inquiry for my form errors now.

I was hoping to have the form error background go up in behind the inputs to look like it is attached/seamless w/ position, but wondering if there's a way to get around the width collapsing or set the width relative to field width because it changes.

If not, I will simplify

**Comment by thomasjbradley** [comment]
I dunno. Maybe the error message needs tag to wrap around the input?

**Comment by trebird** [comment]
Thank you!

**Comment by trebird** [comment]
Virtual hand in!
