### ISSUE TITLE
Image card

### ISSUE THREAD

**Issue by trebird** [trebird/ecommerce-pattern-library#6]
Hi @thomasjbradley,

Just trying out my index.html layout, and realized something is terribly wrong with my image card code. 

I styled w/ position and based numbers on how the card showed up in pattern library. Is there a way to position the colour solid in relation to the image and not the page?

**Comment by thomasjbradley** [comment]
You’re missing `position: relative`. Add the `.relative` class onto the `.image-card` `<div>`

**Comment by trebird** [comment]
Ahhhh the ol' mixer upper.

Success! Thank you
