### ISSUE TITLE
Surprise ecommerce page 1

### ISSUE THREAD

**Issue by trebird** [trebird/ecommerce-pattern-library#7]
Hi @thomasjbradley,

Creating the first surprise ecommerce page was a slightly scary process, but it held up ok. I regret to report that while in a panic adding some styling classes for spacing/padding, I got carried away and instinctively made some type theme changes and experiments as well. However, I realize that was evil and illegal. I've since restored all of the typography theme to the original set up* and happy to say that the page looks more acceptable than I had originally felt when seeing it again. Of course, I would want to make some changes to create more of a visual hierarchy, but I understand that goes against the terms & conditions of this assignment.

*Earlier on in the theme design I had changed the naming of my colour variables, but noticed yesterday I had forgotten to update the names where they were used–ex. any instances of "var(--color-rust)"or "var(--color-charcoal)" should have been updated but weren't. I'm ok to leave them, but wondered if it's alright to update to their proper names.

Thank you

**Comment by thomasjbradley** [comment]
Thanks for the rationale!

**Comment by trebird** [comment]
Fo sho!
